import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        List<Item> items = Arrays.asList(
            new Item("ITEM0001", "Braised chicken", 18.00),
            new Item("ITEM0013", "Chinese hamburger", 6.00),
            new Item("ITEM0022", "Cold noodles", 8.00),
            new Item("ITEM0030", "coca-cola", 2.00)
        );

        List<SalesPromotion> promotions = Arrays.asList(
                new SalesPromotion("BUY_30_SAVE_6_YUAN", "Deduct 6 yuan when the order reaches 30 yuan", Arrays.asList()),
                new SalesPromotion("50%_DISCOUNT_ON_SPECIFIED_ITEMS", "Half price for certain dishes", Arrays.asList(
                        "ITEM0001", "ITEM0022"
                ))
        );

//        System.out.println(item_1.getName());

        String orderSummary =  "============= Order details =============\n";
        int total = 0;
        int discount = 0;
        int promotion2discount = 0;
        for(int i = 0; i < inputs.size(); i++){
            String input = inputs.get(i);
            int subTotal = 0;
            String[] splittedItem = input.split(" ",3);
            for(int j = 0; j < 3; j++){
                if((items.get(j).getId()).equals(splittedItem[0])){
                    total = total + (int) (Integer.parseInt(splittedItem[2]) * items.get(j).getPrice());
                    subTotal = subTotal + (int) (Integer.parseInt(splittedItem[2]) * items.get(j).getPrice());
                    orderSummary = orderSummary +
                            (items.get(j)).getName() + " x " + splittedItem[2] + " = " +
                            total + " yuan" + "\n";
                }
            }
            for(int x = 0; x < promotions.get(1).getRelatedItems().size(); x++){
                if(splittedItem[0].equals(promotions.get(1).getRelatedItems().get(x))){
                    promotion2discount = promotion2discount + subTotal / 2;
                }
            }
        }

        orderSummary = orderSummary + "-----------------------------------\n";

        System.out.println("Test: " + promotion2discount);
        if(6 > promotion2discount){
            orderSummary = orderSummary + "Promotion used:\n" + promotions.get(0).getDisplayName() + "\n";
            total = total - 6;
        }
        else{
            orderSummary = orderSummary + "Promotion used:\n" + promotions.get(1).getDisplayName() + "\n";
            total = total - promotion2discount;
        }

        orderSummary = orderSummary + "-----------------------------------\n";

        orderSummary = orderSummary + "Total：" + total + " yuan\n" +
                "===================================";
        return orderSummary;



//        return "============= Order details =============\n" +
//                "Chinese hamburger x 4 = 24 yuan\n" +
//                "Cold noodles x 1 = 8 yuan\n" +
//                "-----------------------------------\n" +
//                "Promotion used:\n" +
//                "Deduct 6 yuan when the order reaches 30 yuan" +
//                "-----------------------------------\n" +
//                "Total：26 yuan\n" +
//                "===================================";
    }
}